# Generated by Django 3.1 on 2020-08-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_local_name', models.CharField(max_length=100, verbose_name='지역번호')),
                ('p_idx', models.IntegerField(verbose_name='공원번호')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starpoint', models.IntegerField(null=True, verbose_name='별점1~5')),
                ('contents', models.TextField(max_length=500, verbose_name='글내용')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.park_number')),
            ],
        ),
    ]
